DataBase 
-------------------------------------------------------

- what is DataBase?
  - Database server - RDBMS / DBMS / NoSql (MongoDB)
    - SQl-91 Standard to write the queries
      - Database
        -Table
          - Rows and Cols
  Products 
  - Postgresql (pgAdmin4 GUI)
  - MySQL (phpmyqdmin GUI)
  - MarineDB
  - Oracle
  - MsSQL
  ..
  ..

Installation of postgresql

- sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
- sudo apt update
- wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
- sudo apt-get update
- sudo apt-get -y install postgresql
- sudo apt install postgresql-contrib
- To Install pgAdmin4
- curl https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo apt-key add
- sudo sh -c 'echo "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'
- sudo apt update
- sudo apt install pgadmin4
- sudo /usr/pgadmin4/bin/setup-web.sh
- http://SERVER_IP/pgadmin4

once Installation done, create a user, DB and allocate auth
- sudo su - postgres
- psql

  Run following queries
  - CREATE USER samyak3009 WITH PASSWORD '******8';
  - CREATE DATABASE innovaccer;
  - GRANT ALL PRIVILEGES ON DATABASE innovaccer to samyak3009;
  - ALTER USER user_name CREATEDB CREATEROLE LOGIN;

MySQL installation



- Queries
  - CREATE table;
  - Data type
    - Int - Numerical
    - Float
    - Decimal
    - Char (255)
    - Varchar (255)
    - Date
    - Timestamp
    - Time
    - Bool
    - Enum


select * from directors;
select first_name, last_name from directors;
select first_name as f_name, last_name AS l_name from directors;
select * from movies where age_certification = '15';
select * from movies where age_certification = '15' and movie_lang = 'English';
select * from movies where age_certification = '15' or movie_lang = 'English';
select * from movies where movie_length in (121,150,115,112);
select * from movies where movie_length not in (121,150,115,112);
select * from movies where age_certification in ('PG','18','U');
select * from movies where age_certification not in ('PG','18','U');
select * from movies where movies_name like '%Now';
select * from movies where movies_name like '%Now%';
select * from movies where movies_name like 'City of ___';
select * from actors;



 





- Aggregrate function
  - SUM
  - MAX
  - MIN
  - COUNT
  - AVG
-Note : every aggregrate function always ignore the NULL value;

  select * from movies;
  select count(*) from movies;
  select count(movie_id) from movies;
  select sum(domestic_takings) as national_revenue from movies_revenues;
  select MAX(domestic_takings) as maximum_revenue from movies_revenues;
  select MIN(domestic_takings) as minimum_revenue from movies_revenues;
  


# select movie_lang ,count(movie_lang) as no_of_movies from movies group by movie_lang, movie_length having movie_length < avg(movie_length) 



-- String function
  - select UPPER('samyak'); #SAMYAK
  - select LOWER('JAIN'); #jain
  - select INITCAP('samyak jain') #Samyak Jain
  - select *, UPPPER(first_name) as CAP from actors
  - select LEFT('INDIA',4); #INDI
  - select LEFT('INDIA', -3) #IN  (it will remove the last 3 letter)
  - select RIGHT('INDIA',3) #DIA
  - select RIGHT('INDIA',-3) #IA  (it will remove the last 3 letter)
  - select 8,LEFT(movies_name,5) from movies
  - select REVERSE('INDIA')
  - select SUBSTRING('INDIA,2,3) #NDI  (start from 2 and print 3 character)
  - select REPLACE('I AM FROM INDIA','INDIA','USA')
  - select SPLIT_PART('samyak3009@gmail.com','@',1) #samyak3009
  - select date_of_birth from directors
  - select SPLIT_PART(date_of_birth::TEXT,'-',1) from directors
  - select SPLIT_PART(date_of_birth::varchar(50),'-',1) from directors
  - select SPLIT_PART(date_of_birth::varchar(2),'-',1) from directors
  - select REPLACE(date_of_birth::varchar(10),'-','/') from directors
  -  

